# Health Analytics Naïve Bayes

## Loading in Data

In [1]:
import pandas as pd, numpy as np
from sklearn.linear_model import LogisticRegression

In [2]:
train = pd.read_csv('train_aj.csv')
test = pd.read_csv('test_v2.csv')
subm = pd.read_csv('s_sub.csv')

## Processing data

In [13]:
train_new = pd.read_csv('train_new.csv')
test_new = pd.read_csv('test_new.csv')
train_new2 = pd.read_csv('train_new2.csv')
test_new2 = pd.read_csv('test_new2.csv')

In [14]:
train_x = train_new.drop(["stroke","id"],axis=1)
train_y = train_new["stroke"]
test_x = test_new.iloc[:,1:]

In [15]:
train_x2 = train_new2.drop(["stroke","id"],axis=1)
train_y2 = train_new2["stroke"]
test_x2 = test_new2.iloc[:,1:]

## Building Model

In [5]:
def bnb(y_i, y):
    p = train_x[y==y_i].sum(0)
    return (p+1) / ((y==y_i).sum()+1)

In [6]:
def get_mdl(y):
    y = y.values
    r = np.log(bnb(1,y) / bnb(0,y))
    m = LogisticRegression(C=4, dual=True)
    x_nb = train_x.multiply(r)
    return m.fit(x_nb, y), r

In [9]:
preds = np.zeros((len(test_x), 2))
m,r = get_mdl(train_y)
preds[:,1] = m.predict_proba(test_x.multiply(r))[:,1]

## Building model 2

In [19]:
def bnb2(y_i, y):
    p = train_x2[y==y_i].sum(0)
    return (p+1) / ((y==y_i).sum()+1)

In [20]:
def get_mdl2(y):
    y = y.values
    r = np.log(bnb2(1,y) / bnb2(0,y))
    m = LogisticRegression(C=4, dual=True)
    x_nb = train_x2.multiply(r)
    return m.fit(x_nb, y), r

In [21]:
preds2 = np.zeros((len(test_x2), 2))
m,r = get_mdl2(train_y2)
preds2[:,1] = m.predict_proba(test_x2.multiply(r))[:,1]

## Submission

In [24]:
preds[:,0] = test.iloc[:,0]
submis = pd.DataFrame(preds, columns = ["id","stroke"])
pd.concat([submis], axis=1)

submis.to_csv('nbayes.csv', index=False)

            id    stroke
0      36306.0  0.007199
1      61829.0  0.011010
2      14152.0  0.000210
3      12997.0  0.000644
4      40801.0  0.002477
5       9348.0  0.004693
6      51550.0  0.001351
7      60512.0  0.001031
8      31309.0  0.004655
9      39199.0  0.005891
10     15160.0  0.000359
11     21705.0  0.000177
12     19042.0  0.001137
13     12249.0  0.000811
14     33104.0  0.003097
15     55264.0  0.002020
16     29445.0  0.003607
17     49013.0  0.000394
18       276.0  0.000229
19     47721.0  0.000597
20     19656.0  0.003827
21     35806.0  0.001059
22     70637.0  0.001045
23     62010.0  0.000211
24     67576.0  0.005501
25     31774.0  0.011956
26     43822.0  0.000946
27     27445.0  0.000893
28     35817.0  0.001977
29     26363.0  0.005960
...        ...       ...
18571  30015.0  0.005617
18572  24761.0  0.000741
18573  27094.0  0.000340
18574  43495.0  0.000121
18575  56348.0  0.001405
18576  11876.0  0.000516
18577    585.0  0.001768
18578  43879.0  0.000512
18579  38239.0  0.000492
18580  28943.0  0.000122
18581  17895.0  0.000413
18582  35147.0  0.008563
18583  72758.0  0.001009
18584  28661.0  0.000154
18585  46853.0  0.000411
18586  69190.0  0.000498
18587  26705.0  0.015208
18588  36976.0  0.009424
18589  58578.0  0.000555
18590  61508.0  0.001612
18591  70296.0  0.000271
18592  35299.0  0.000211
18593  15023.0  0.006624
18594  56291.0  0.001548
18595  53431.0  0.000152
18596  67353.0  0.000490
18597    362.0  0.002445
18598  29839.0  0.005276
18599   6438.0  0.001590
18600  16770.0  0.000975

[18601 rows x 2 columns]

In [23]:
preds2[:,0] = test.iloc[:,0]
submis2 = pd.DataFrame(preds2, columns = ["id","stroke"])
pd.concat([submis2], axis=1)

submis2.to_csv('nbayes2.csv', index=False)

## Blend